# Build the plugin before building this image:
#   npm install && npm run build
# Then start the stack:
#   docker-compose up --build

ARG KIBANA_VERSION=9.3.4
FROM docker.elastic.co/kibana/kibana:${KIBANA_VERSION}

USER root
COPY target/babel /usr/share/kibana/plugins/babel
RUN chown -R kibana:kibana /usr/share/kibana/plugins/babel
USER kibana
