"""
Pytest fixtures and configuration for API tests.
"""

import pytest
from unittest.mock import MagicMock, patch
from fastapi.testclient import TestClient
from main import app
import os

# Force auth on for all tests so auth-guard tests work correctly.
# The lru_cache on get_settings() is cleared after each test via autouse fixture.
os.environ.setdefault("REQUIRE_AUTH", "true")


# ── App client ────────────────────────────────────────────────────────────────

@pytest.fixture(autouse=True)
def _reset_settings_cache():
    """Clear lru_cache on get_settings() between tests so env patches take effect."""
    from config import get_settings
    get_settings.cache_clear()
    yield
    get_settings.cache_clear()


@pytest.fixture
def client():
    return TestClient(app, raise_server_exceptions=False)


# ── Auth ──────────────────────────────────────────────────────────────────────

@pytest.fixture
def valid_api_key():
    return "ZWxhc3RpYzp0ZXN0a2V5"  # base64: elastic:testkey


@pytest.fixture
def auth(valid_api_key):
    return {"Authorization": f"Bearer {valid_api_key}"}


# Legacy alias used by existing tests
@pytest.fixture
def headers_with_auth(auth):
    return auth


# ── Sigma rules ───────────────────────────────────────────────────────────────

@pytest.fixture
def sample_sigma_rule():
    return """title: Test Rule
description: A test detection rule
detection:
  selection:
    Image|endswith: 'test.exe'
    CommandLine|contains: 'suspicious'
  condition: selection
"""


@pytest.fixture
def titled_sigma_rule():
    return """title: Suspicious PowerShell Execution
status: experimental
description: Detects suspicious PowerShell usage
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: '\\powershell.exe'
        CommandLine|contains:
            - '-EncodedCommand'
            - '-enc '
    condition: selection
level: high
tags:
    - attack.t1059.001
    - attack.execution
falsepositives:
    - Legitimate admin scripts
"""


# ── Elasticsearch mock ────────────────────────────────────────────────────────

def make_es_mock(search_hits=None, get_source=None, index_exists=False):
    """
    Build a configured MagicMock that behaves like an Elasticsearch client.
    search_hits: list of _source dicts to return from client.search()
    get_source:  _source dict to return from client.get()
    """
    mock = MagicMock()

    # Index management
    mock.indices.exists.return_value = index_exists
    mock.indices.create.return_value = {"acknowledged": True}
    mock.indices.get_mapping.return_value = {
        "logs-2024.01.01": {
            "mappings": {
                "properties": {
                    "process": {
                        "properties": {
                            "name": {"type": "keyword"},
                            "executable": {"type": "keyword"},
                            "command_line": {"type": "text"},
                        }
                    },
                    "user": {"properties": {"name": {"type": "keyword"}}},
                    "host": {"properties": {"name": {"type": "keyword"}}},
                    "@timestamp": {"type": "date"},
                    "event": {"properties": {"code": {"type": "keyword"}}},
                }
            }
        }
    }

    # Document operations
    mock.index.return_value = {"result": "created", "_id": "test-id"}

    hits = search_hits or []
    mock.search.return_value = {
        "hits": {
            "total": {"value": len(hits)},
            "hits": [{"_id": f"id-{i}", "_source": h, "_index": "logs-2024"} for i, h in enumerate(hits)],
        },
        "aggregations": {},
    }

    if get_source:
        mock.get.return_value = {"_id": "test-id", "_source": get_source}
    else:
        from elasticsearch.exceptions import NotFoundError
        mock.get.side_effect = NotFoundError(404, "not found", {})

    mock.close.return_value = None
    return mock


@pytest.fixture
def mock_es(monkeypatch):
    """
    Patches Elasticsearch in all service modules.
    Returns a factory so individual tests can configure the mock.
    """
    es_instance = make_es_mock()

    def _patch(module_path):
        monkeypatch.setattr(f"{module_path}.Elasticsearch", lambda *a, **kw: es_instance)

    for mod in [
        "services.effectiveness",
        "services.schema_drift",
        "services.rule_registry",
        "services.ai_context",
        "services.testing",
    ]:
        _patch(mod)

    return es_instance


# ── Anthropic mock ────────────────────────────────────────────────────────────

MOCK_SIGMA_YAML = """title: Mocked AI Rule
status: experimental
description: Generated by mock LLM
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        CommandLine|contains: 'evil.exe'
    condition: selection
level: high
"""

MOCK_EXPLANATION = "**What it detects:** Suspicious process execution.\n**MITRE ATT&CK:** T1059"
MOCK_CHANGES = "- Tightened CommandLine filter to reduce false positives"


def _make_anthropic_mock(response_text: str, monkeypatch):
    """
    Patch the anthropic module used by ai_generator._make_client().
    The function does `import anthropic; return anthropic.Anthropic(...)`,
    so we patch the top-level `anthropic` module's `Anthropic` class.
    """
    mock_client = MagicMock()
    mock_message = MagicMock()
    mock_message.content = [MagicMock(text=response_text)]
    mock_client.messages.create.return_value = mock_message

    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-ant-test-key")

    import anthropic as anthropic_module
    monkeypatch.setattr(anthropic_module, "Anthropic", lambda **kw: mock_client)

    return mock_client


@pytest.fixture
def mock_anthropic(monkeypatch):
    """Patches the Anthropic client so no real API calls are made."""
    return _make_anthropic_mock(MOCK_SIGMA_YAML, monkeypatch)


@pytest.fixture
def mock_anthropic_explain(monkeypatch):
    """Anthropic mock that returns an explanation instead of YAML."""
    return _make_anthropic_mock(MOCK_EXPLANATION, monkeypatch)


@pytest.fixture
def mock_anthropic_improve(monkeypatch):
    """Anthropic mock that returns improved YAML + changes section."""
    return _make_anthropic_mock(f"{MOCK_SIGMA_YAML}\n---CHANGES---\n{MOCK_CHANGES}", monkeypatch)
