"""
Tests for AI-assisted detection engineering routes and services.

All tests use mocked Anthropic and Elasticsearch clients so no real
API calls or ES connections are made.
"""

import pytest
from unittest.mock import MagicMock
from elasticsearch.exceptions import NotFoundError

MOCK_SIGMA_YAML = """title: Mocked AI Rule
status: experimental
description: Generated by mock LLM
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        CommandLine|contains: 'evil.exe'
    condition: selection
level: high
"""
MOCK_EXPLANATION = "**What it detects:** Suspicious process execution.\n**MITRE ATT&CK:** T1059"
MOCK_CHANGES = "- Tightened CommandLine filter to reduce false positives"


# ── Helpers ───────────────────────────────────────────────────────────────────

KIBANA_ALERT_DOC = {
    "@timestamp": "2024-01-15T12:00:00Z",
    "kibana.alert.rule.name": "Malicious PowerShell",
    "kibana.alert.severity": "high",
    "host": {"name": "desktop-001"},
    "process": {"name": "powershell.exe", "command_line": "-enc SGVsbG8="},
}

SO_ALERT_DOC = {
    "@timestamp": "2024-01-15T12:00:00Z",
    "rule": {"sid": "2001234", "name": "ET MALWARE Cobalt Strike"},
    "event": {"module": "suricata", "severity": 1},
    "host": {"name": "sensor-01"},
}


# ── POST /v1/ai/draft-from-iocs ───────────────────────────────────────────────

def test_draft_from_iocs_returns_rule_yaml(client, auth, mock_es, mock_anthropic, sample_sigma_rule):
    resp = client.post(
        "/v1/ai/draft-from-iocs",
        json={
            "iocs": ["evil.exe", "192.168.1.100"],
            "index_pattern": "logs-*",
        },
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    assert "rule_yaml" in data
    assert "Mocked AI Rule" in data["rule_yaml"]


def test_draft_from_iocs_with_logsource_hint(client, auth, mock_es, mock_anthropic):
    resp = client.post(
        "/v1/ai/draft-from-iocs",
        json={
            "iocs": ["bad.exe"],
            "index_pattern": "logs-*",
            "logsource_hint": "process_creation",
        },
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    # Confirm the logsource hint was forwarded to Claude
    call_args = mock_anthropic.messages.create.call_args
    assert "process_creation" in str(call_args)


def test_draft_from_iocs_missing_iocs(client, auth):
    resp = client.post(
        "/v1/ai/draft-from-iocs",
        json={"index_pattern": "logs-*"},
        headers=auth,
    )
    assert resp.status_code == 422


def test_draft_from_iocs_no_api_key(client, auth, mock_es, monkeypatch):
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    resp = client.post(
        "/v1/ai/draft-from-iocs",
        json={"iocs": ["evil.exe"], "index_pattern": "logs-*"},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    # RuntimeError from missing key should be caught and returned as success=False
    assert data["success"] is False
    assert "message" in data


# ── POST /v1/ai/explain ───────────────────────────────────────────────────────

def test_explain_rule_returns_explanation(client, auth, mock_anthropic_explain, titled_sigma_rule):
    resp = client.post(
        "/v1/ai/explain",
        json={"rule_yaml": titled_sigma_rule},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    assert "explanation" in data
    assert "Suspicious process execution" in data["explanation"]


def test_explain_rule_missing_body(client, auth):
    resp = client.post("/v1/ai/explain", json={}, headers=auth)
    assert resp.status_code == 422


def test_explain_rule_calls_claude_once(client, auth, mock_anthropic_explain, sample_sigma_rule):
    client.post(
        "/v1/ai/explain",
        json={"rule_yaml": sample_sigma_rule},
        headers=auth,
    )
    mock_anthropic_explain.messages.create.assert_called_once()


# ── POST /v1/ai/improve ───────────────────────────────────────────────────────

def test_improve_rule_returns_yaml_and_changes(client, auth, mock_es, mock_anthropic_improve, titled_sigma_rule):
    resp = client.post(
        "/v1/ai/improve",
        json={"rule_yaml": titled_sigma_rule, "index_pattern": "logs-*"},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    assert "rule_yaml" in data
    assert "Mocked AI Rule" in data["rule_yaml"]
    assert "changes" in data
    assert "CommandLine filter" in data["changes"]


def test_improve_rule_splits_on_separator(client, auth, mock_es, mock_anthropic_improve, sample_sigma_rule):
    resp = client.post(
        "/v1/ai/improve",
        json={"rule_yaml": sample_sigma_rule, "index_pattern": "logs-*"},
        headers=auth,
    )
    data = resp.json()
    assert data["success"] is True
    # The mock returns YAML + ---CHANGES--- + changes text; both should be present
    assert data["rule_yaml"] != data.get("changes", "")


def test_improve_rule_missing_index_pattern_uses_default(client, auth, mock_es, mock_anthropic_improve, sample_sigma_rule):
    resp = client.post(
        "/v1/ai/improve",
        json={"rule_yaml": sample_sigma_rule},
        headers=auth,
    )
    # Should succeed even without index_pattern (default applied in service)
    assert resp.status_code in (200, 422)


# ── POST /v1/ai/draft-from-alert (kibana) ────────────────────────────────────

def test_draft_from_kibana_alert(client, auth, mock_es, mock_anthropic):
    mock_es.get.side_effect = None
    mock_es.get.return_value = {"_id": "alert-001", "_source": KIBANA_ALERT_DOC}

    resp = client.post(
        "/v1/ai/draft-from-alert",
        json={"alert_id": "alert-001", "source": "kibana"},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    assert "rule_yaml" in data


def test_draft_from_kibana_alert_not_found(client, auth, mock_es, mock_anthropic):
    # Both get() and search() return no hits
    mock_es.get.side_effect = NotFoundError(404, "not found", {})
    mock_es.search.return_value = {
        "hits": {"total": {"value": 0}, "hits": []},
        "aggregations": {},
    }
    resp = client.post(
        "/v1/ai/draft-from-alert",
        json={"alert_id": "nonexistent", "source": "kibana"},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is False
    assert "not found" in data["message"].lower()


# ── POST /v1/ai/draft-from-alert (security onion) ────────────────────────────

def test_draft_from_so_alert_suricata(client, auth, mock_es, mock_anthropic):
    mock_es.search.return_value = {
        "hits": {
            "total": {"value": 1},
            "hits": [{"_id": "so-alert-001", "_source": SO_ALERT_DOC, "_index": "so-alert-2024"}],
        },
        "aggregations": {},
    }
    resp = client.post(
        "/v1/ai/draft-from-alert",
        json={"alert_id": "so-alert-001", "source": "so"},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    assert data.get("source_type") == "suricata"


def test_draft_from_so_alert_zeek(client, auth, mock_es, mock_anthropic):
    zeek_doc = {
        "@timestamp": "2024-01-15T12:00:00Z",
        "event": {"module": "zeek"},
        "source": {"ip": "10.0.0.1"},
    }
    mock_es.search.return_value = {
        "hits": {
            "total": {"value": 1},
            "hits": [{"_id": "zeek-001", "_source": zeek_doc, "_index": "so-logs-2024"}],
        },
        "aggregations": {},
    }
    resp = client.post(
        "/v1/ai/draft-from-alert",
        json={"alert_id": "zeek-001", "source": "so"},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is True
    assert data.get("source_type") == "zeek"


def test_draft_from_so_alert_not_found(client, auth, mock_es, mock_anthropic):
    mock_es.search.return_value = {
        "hits": {"total": {"value": 0}, "hits": []},
        "aggregations": {},
    }
    resp = client.post(
        "/v1/ai/draft-from-alert",
        json={"alert_id": "missing", "source": "so"},
        headers=auth,
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["success"] is False


def test_draft_from_alert_missing_fields(client, auth):
    resp = client.post("/v1/ai/draft-from-alert", json={}, headers=auth)
    assert resp.status_code == 422


# ── GET /v1/ai/alerts ─────────────────────────────────────────────────────────

def test_list_kibana_alerts(client, auth, mock_es):
    mock_es.search.return_value = {
        "hits": {
            "total": {"value": 2},
            "hits": [
                {
                    "_id": "alert-1",
                    "_source": {
                        "@timestamp": "2024-01-15T12:00:00Z",
                        "kibana.alert.rule.name": "Rule A",
                        "kibana.alert.severity": "high",
                        "host": {"name": "host-1"},
                    },
                    "_index": ".alerts-security.alerts-default",
                },
                {
                    "_id": "alert-2",
                    "_source": {
                        "@timestamp": "2024-01-15T11:00:00Z",
                        "kibana.alert.rule.name": "Rule B",
                        "kibana.alert.severity": "medium",
                        "host": {"name": "host-2"},
                    },
                    "_index": ".alerts-security.alerts-default",
                },
            ],
        },
        "aggregations": {},
    }
    resp = client.get("/v1/ai/alerts", params={"source": "kibana"}, headers=auth)
    assert resp.status_code == 200
    data = resp.json()
    assert data["index_pattern"] == ".alerts-security.alerts-default"
    assert len(data["alerts"]) == 2
    assert data["alerts"][0]["id"] == "alert-1"
    assert data["alerts"][0]["severity"] == "high"


def test_list_so_alerts(client, auth, mock_es):
    mock_es.search.return_value = {
        "hits": {
            "total": {"value": 1},
            "hits": [
                {
                    "_id": "so-1",
                    "_source": {
                        "@timestamp": "2024-01-15T10:00:00Z",
                        "rule": {"name": "ET SCAN"},
                        "event": {"module": "suricata", "severity": "medium"},
                        "host": {"name": "sensor-1"},
                    },
                    "_index": "so-alert-2024",
                }
            ],
        },
        "aggregations": {},
    }
    resp = client.get("/v1/ai/alerts", params={"source": "so"}, headers=auth)
    assert resp.status_code == 200
    data = resp.json()
    assert data["index_pattern"] == "so-alert-*"
    assert len(data["alerts"]) == 1
    assert data["alerts"][0]["id"] == "so-1"
    assert data["alerts"][0]["event_module"] == "suricata"


def test_list_alerts_empty(client, auth, mock_es):
    mock_es.search.return_value = {
        "hits": {"total": {"value": 0}, "hits": []},
        "aggregations": {},
    }
    resp = client.get("/v1/ai/alerts", headers=auth)
    assert resp.status_code == 200
    assert resp.json()["alerts"] == []


def test_list_alerts_size_param(client, auth, mock_es):
    mock_es.search.return_value = {
        "hits": {"total": {"value": 0}, "hits": []},
        "aggregations": {},
    }
    resp = client.get("/v1/ai/alerts", params={"size": 5}, headers=auth)
    assert resp.status_code == 200
    # Verify size was forwarded (search was called with the right body)
    call_body = mock_es.search.call_args[1].get("body", {})
    assert call_body.get("size") == 5


# ── Auth guard ────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("method,path,body", [
    ("post", "/v1/ai/explain", {"rule_yaml": "title: x\n"}),
    ("post", "/v1/ai/draft-from-iocs", {"iocs": ["x"], "index_pattern": "logs-*"}),
    ("get",  "/v1/ai/alerts", None),
])
def test_ai_routes_require_auth(client, method, path, body):
    if method == "post":
        resp = client.post(path, json=body)
    else:
        resp = client.get(path)
    assert resp.status_code == 401
